apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  
  labels:
    app: {{ .Values.service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      name: fedco-devcentral-app-pod
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
      - name: fedco-devcentral-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
          - containerPort: {{ .Values.service.port }}
        imagePullPolicy: Always
        volumeMounts:
          - name: config-js-volume
            mountPath: /app/build/config.js
            subPath: config.js


      volumes:
        - name: config-js-volume
          configMap:
            name: {{ .Values.configMap.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  
spec:
  selector:
    app: {{ .Values.service.name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
