environments:
  local:
  dev:
  stage:
releases:
    - name: fedco-devcentral-app-{{ .Environment.Name }}
      chart: ./charts/fedco-devcentral-app
      values:
          -  ./values/values-{{ .Environment.Name }}.yaml


    
