apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fedco.fullname" . }}
  
  labels:
    app: {{ include "fedco.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "fedco.fullname" . }}
  template:
    metadata:
      name: fedco-devcentral-app
      labels:
        app: {{ include "fedco.fullname" . }}
    spec:
      containers:
      - name: fedco
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
          - containerPort: {{ .Values.service.port }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - name: config-js-volume
            mountPath: /app/build/config.js
            subPath: config.js


      volumes:
        - name: config-js-volume
          configMap:
            name: {{ .Values.configMap.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fedco.fullname" . }}
  
spec:
  selector:
    app: {{ include "fedco.fullname" . }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
