apiVersion: v1
kind: Service
metadata:
  name: {{ include "fedco-devcentral-app.fullname" . }}
  
spec:
  selector:
    app: {{ include "fedco-devcentral-app.fullname" . }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP